### ISSUE TITLE
Correcciones Vistas

### ISSUE THREAD

**Issue by AngelaGAlvarez** [Arquisoft/Trivial2a#3]
Eliminar marcas de agua.
Modificar el tamaño de caja o aumentar el tamaño del texto.
Poner los autores bien. 
Redactar relaciones.

**Comment by MariaPiris** [comment]
Está modificado el tamaño de caja y de letra de los diagramas en el proyecto de visualParadigm

**Comment by MariaPiris** [comment]
Hechas correcciones
